# Generated by Django 5.1.1 on 2024-09-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_grill_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=150, verbose_name='Телефон на сайт (красивый)')),
                ('whatsapp', models.CharField(max_length=150, verbose_name='Телефон для whatsApp')),
                ('telegram', models.CharField(max_length=150, verbose_name='Для telegram')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
